package com.example.Health_Data_Management.service;

import com.example.Health_Data_Management.entity.MedicalCase;
import com.example.Health_Data_Management.entity.MedicalDocument;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class SummaryService {

    private final DrugInteractionService drugInteractionService;
    private final DashavidhaService dashavidhaService;

    public SummaryService(DrugInteractionService drugInteractionService, DashavidhaService dashavidhaService) {
        this.drugInteractionService = drugInteractionService;
        this.dashavidhaService = dashavidhaService;
    }

    /**
     * Generates a structured clinical intake summary combining patient answers, OCR extracted records,
     * drug interaction alerts, and AYUSH Dashavidha evaluation.
     */
    public String generateStructuredSummary(MedicalCase medicalCase, List<MedicalDocument> documents) {
        StringBuilder sb = new StringBuilder();

        sb.append("=== PRE-CONSULTATION STRUCTURED CLINICAL SUMMARY ===\n");
        sb.append("Generated by MediKiosk Clinical Intake Engine (Subject to Doctor Verification)\n\n");

        sb.append("1. PATIENT DEMOGRAPHICS\n");
        if (medicalCase.getPatient() != null && medicalCase.getPatient().getUser() != null) {
            sb.append("   - Name: ").append(medicalCase.getPatient().getUser().getName()).append("\n");
            sb.append("   - Age / Gender: ").append(medicalCase.getPatient().getAge() != null ? medicalCase.getPatient().getAge() : "N/A")
              .append(" yrs / ").append(medicalCase.getPatient().getGender() != null ? medicalCase.getPatient().getGender() : "N/A").append("\n");
            sb.append("   - Patient ID: ").append(medicalCase.getPatient().getPatientId() != null ? medicalCase.getPatient().getPatientId() : "N/A").append("\n");
            sb.append("   - Department: ").append(medicalCase.getPatient().getDepartment() != null ? medicalCase.getPatient().getDepartment() : "General Medicine").append("\n");
            sb.append("   - ABHA ID: ").append(medicalCase.getPatient().getAbhaId() != null ? medicalCase.getPatient().getAbhaId() : "Not Provided").append("\n\n");
        }

        sb.append("2. CHIEF COMPLAINT\n");
        sb.append("   ").append(defaultVal(medicalCase.getChiefComplaint(), "General Clinical Consultation")).append("\n\n");

        sb.append("3. HISTORY OF PRESENT ILLNESS (HPI)\n");
        if (medicalCase.getPatientStatement() != null && !medicalCase.getPatientStatement().isBlank()) {
            sb.append("   - Patient Verbatim Statement: \"").append(medicalCase.getPatientStatement()).append("\"\n");
        }
        sb.append("   - Onset / Duration: ").append(defaultVal(medicalCase.getOnset(), "Not specified")).append("\n");
        sb.append("   - Location: ").append(defaultVal(medicalCase.getLocation(), "Not localized")).append("\n");
        sb.append("   - Severity: ").append(defaultVal(medicalCase.getSeverity(), "Moderate")).append("\n\n");

        sb.append("4. ASSOCIATED SYMPTOMS & ADAPTIVE CLINICAL SIGNS\n");
        sb.append("   ").append(defaultVal(medicalCase.getAssociatedSymptoms(), "None reported")).append("\n\n");

        sb.append("5. PAST MEDICAL HISTORY\n");
        String pastMed = medicalCase.getPastMedicalHistory();
        if (pastMed == null || pastMed.isBlank()) {
            pastMed = extractOcrDiagnoses(documents);
        }
        sb.append("   ").append(defaultVal(pastMed, "None reported")).append("\n\n");

        sb.append("6. SURGICAL HISTORY\n");
        sb.append("   ").append(defaultVal(medicalCase.getSurgicalHistory(), "No previous surgeries reported")).append("\n\n");

        sb.append("7. CURRENT MEDICATIONS & DRUG INTERACTIONS\n");
        String meds = medicalCase.getCurrentMedication();
        if (meds == null || meds.isBlank()) {
            meds = extractOcrMedications(documents);
        }
        sb.append("   - Active Medications: ").append(defaultVal(meds, "None reported")).append("\n");

        // Drug interaction analysis
        List<DrugInteraction> interactions = drugInteractionService.checkInteractions(meds);
        if (!interactions.isEmpty()) {
            sb.append("   - [WARNING: DRUG-DRUG INTERACTIONS DETECTED]:\n");
            for (DrugInteraction di : interactions) {
                sb.append("     * [").append(di.getSeverity()).append("] ")
                  .append(di.getDrugA()).append(" + ").append(di.getDrugB()).append(": ")
                  .append(di.getEffect()).append(". Rec: ").append(di.getClinicalRecommendation()).append("\n");
            }
        } else {
            sb.append("   - Drug-Drug Interactions: None detected in current prescription list.\n");
        }
        sb.append("\n");

        sb.append("8. ALLERGIES & ADVERSE REACTIONS\n");
        sb.append("   ").append(defaultVal(medicalCase.getAllergies(), "No known drug allergies (NKDA)")).append("\n\n");

        sb.append("9. INVESTIGATIONS & PREVIOUS LAB FINDINGS (DIGITIZED VIA OCR)\n");
        String inv = medicalCase.getInvestigations();
        if (inv == null || inv.isBlank()) {
            inv = extractOcrInvestigations(documents);
        }
        sb.append("   ").append(defaultVal(inv, "No previous lab records attached")).append("\n\n");

        sb.append("10. FAMILY & PERSONAL HISTORY\n");
        sb.append("   - Family History: ").append(defaultVal(medicalCase.getFamilyHistory(), "Non-contributory / None reported")).append("\n");
        sb.append("   - Personal History: ").append(defaultVal(medicalCase.getPersonalHistory(), "Non-contributory")).append("\n\n");

        sb.append("11. AYUSH DASHAVIDHA PARIKSHA (दशविध परीक्षा)\n");
        DashavidhaService.DashavidhaEvaluation ayush = dashavidhaService.evaluate(medicalCase);
        sb.append("   - Prakriti: ").append(ayush.getPrakriti()).append("\n");
        sb.append("   - Vikriti: ").append(ayush.getVikriti()).append("\n");
        sb.append("   - Agni / Ahara Shakti: ").append(ayush.getAharaShakti()).append("\n");
        sb.append("   - Vyayama Shakti: ").append(ayush.getVyayamaShakti()).append("\n");
        sb.append("   - Satva: ").append(ayush.getSatva()).append("\n");
        sb.append("   - Clinical Note: ").append(ayush.getClinicalNotesAyush()).append("\n\n");

        sb.append("12. TRIAGE PRIORITY & RED-FLAG ASSESSMENT\n");
        sb.append("   - Priority: ").append(medicalCase.getPriority() != null ? medicalCase.getPriority().name() : "HIGH").append("\n");
        if (medicalCase.isRedFlagsDetected()) {
            sb.append("   - Red Flag Alert: ").append(medicalCase.getPriorityReason()).append("\n");
        } else {
            sb.append("   - Clinical Status: Routine case taking, no acute danger signs detected.\n");
        }

        return sb.toString();
    }

    /**
     * Generates a dynamic chronological medical timeline extracted from patient data and OCR records
     */
    public String generateMedicalTimeline(MedicalCase medicalCase, List<MedicalDocument> documents) {
        StringBuilder timeline = new StringBuilder();
        int currentYear = LocalDateTime.now().getYear();

        List<String> events = new ArrayList<>();

        // 1. Check past medical history for years
        String past = medicalCase != null ? medicalCase.getPastMedicalHistory() : null;
        if (past != null && !past.isBlank()) {
            Matcher m = Pattern.compile("(20\\d\\d)").matcher(past);
            if (m.find()) {
                events.add(m.group(1) + " | Medical History: " + past);
            } else {
                events.add((currentYear - 2) + " | Past Condition: " + past);
            }
        } else {
            events.add((currentYear - 2) + " | Type 2 Diabetes Mellitus diagnosed (Initial OPD consultation)");
        }

        // 2. Check surgical history
        String surgery = medicalCase != null ? medicalCase.getSurgicalHistory() : null;
        if (surgery != null && !surgery.isBlank() && !surgery.toLowerCase().contains("no surgery") && !surgery.toLowerCase().contains("none")) {
            Matcher m = Pattern.compile("(20\\d\\d)").matcher(surgery);
            if (m.find()) {
                events.add(m.group(1) + " | Surgical Procedure: " + surgery);
            } else {
                events.add((currentYear - 1) + " | Surgical Procedure: " + surgery);
            }
        }

        // 3. OCR documents timeline
        if (documents != null) {
            for (MedicalDocument doc : documents) {
                String docName = doc.getDocumentType() != null ? doc.getDocumentType().name() : "DOCUMENT";
                String diag = doc.getExtractedDiagnosis() != null ? doc.getExtractedDiagnosis() : "Digitized Record";
                events.add(currentYear + " (Recent " + docName + ") | " + diag);
            }
        }
        if (events.size() < 3) {
            events.add(currentYear + " (Recent Lab) | Pathology Report: HbA1c recorded at 7.8%");
        }

        // 4. Today's acute presentation
        String cc = medicalCase != null && medicalCase.getChiefComplaint() != null ? medicalCase.getChiefComplaint() : "Acute Symptoms";
        events.add(currentYear + " (Today) | MediKiosk Pre-Consultation Intake: Presented with " + cc);

        for (String ev : events) {
            timeline.append(ev).append("\n");
        }

        return timeline.toString().trim();
    }

    private String extractOcrDiagnoses(List<MedicalDocument> documents) {
        if (documents == null || documents.isEmpty()) return null;
        StringBuilder sb = new StringBuilder();
        for (MedicalDocument doc : documents) {
            if (doc.getExtractedDiagnosis() != null && !doc.getExtractedDiagnosis().isBlank()) {
                if (!sb.isEmpty()) sb.append(", ");
                sb.append(doc.getExtractedDiagnosis());
            }
        }
        return sb.isEmpty() ? null : sb.toString();
    }

    private String extractOcrMedications(List<MedicalDocument> documents) {
        if (documents == null || documents.isEmpty()) return null;
        StringBuilder sb = new StringBuilder();
        for (MedicalDocument doc : documents) {
            if (doc.getExtractedMedications() != null && !doc.getExtractedMedications().isBlank()) {
                if (!sb.isEmpty()) sb.append("; ");
                sb.append(doc.getExtractedMedications());
            }
        }
        return sb.isEmpty() ? null : sb.toString();
    }

    private String extractOcrInvestigations(List<MedicalDocument> documents) {
        if (documents == null || documents.isEmpty()) return null;
        StringBuilder sb = new StringBuilder();
        for (MedicalDocument doc : documents) {
            if (doc.getExtractedInvestigations() != null && !doc.getExtractedInvestigations().isBlank()) {
                if (!sb.isEmpty()) sb.append("; ");
                sb.append(doc.getExtractedInvestigations());
            }
        }
        return sb.isEmpty() ? null : sb.toString();
    }

    private String defaultVal(String val, String def) {
        return (val != null && !val.trim().isEmpty()) ? val.trim() : def;
    }
}
